### ISSUE TITLE
Failure to generate guides when CFD scores are to be calculated on locally (and publicly?) hosted client.

### ISSUE THREAD

**Issue by marcus-r-kelly** [pinellolab/PrimeDesign#3]
Hello,

I am once again trying to calculate CFD scores for a set of guides, but if I have "Calculate CFD score" switched to "Yes", then there is no output. This seems to be true for the publicly hosted client, and it is certainly true for the locally hosted client. Here is my terminal output as I first change my desired settings in "Prime editing parameters" and then paste in the correctly formated sequence and edit:
`
[2021-02-27 00:39:27 +0000] [8] [INFO] Starting gunicorn 20.0.4
[2021-02-27 00:39:27 +0000] [8] [INFO] Listening at: http://0.0.0.0:9994 (8)
[2021-02-27 00:39:27 +0000] [8] [INFO] Using worker: sync
[2021-02-27 00:39:27 +0000] [10] [INFO] Booting worker with pid: 10
[2021-02-27 00:39:27 +0000] [11] [INFO] Booting worker with pid: 11
[2021-02-27 00:39:27 +0000] [12] [INFO] Booting worker with pid: 12
[2021-02-27 00:39:27 +0000] [13] [INFO] Booting worker with pid: 13
172.17.0.1 - - [27/Feb/2021:00:39:32 +0000] "GET / HTTP/1.1" 200 618 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:33 +0000] "GET /_dash-dependencies HTTP/1.1" 200 1205 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:33 +0000] "GET /_dash-layout HTTP/1.1" 200 568 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:33 +0000] "POST /_dash-update-component HTTP/1.1" 200 3528 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:33 +0000] "POST /_dash-update-component HTTP/1.1" 200 42 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:33 +0000] "POST /_dash-update-component HTTP/1.1" 200 3528 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:33 +0000] "POST /_dash-update-component HTTP/1.1" 200 40 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 146 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 63 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 147 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 83 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 263 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 349 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 63 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 69 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 75 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 83 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 349 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 263 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:34 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:35 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:35 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:35 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:42 +0000] "POST /_dash-update-component HTTP/1.1" 200 63 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:42 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:42 +0000] "POST /_dash-update-component HTTP/1.1" 200 349 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:42 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:42 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:42 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:42 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:45 +0000] "POST /_dash-update-component HTTP/1.1" 200 63 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:45 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:45 +0000] "POST /_dash-update-component HTTP/1.1" 200 349 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:46 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:46 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:46 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:46 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:46 +0000] "POST /_dash-update-component HTTP/1.1" 200 63 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:47 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:47 +0000] "POST /_dash-update-component HTTP/1.1" 200 349 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:47 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:47 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:47 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:47 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:49 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:49 +0000] "POST /_dash-update-component HTTP/1.1" 200 349 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:50 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:50 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:50 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:50 +0000] "POST /_dash-update-component HTTP/1.1" 200 37 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
ERROR! /PrimeDesign/hg38_chromosomes is not a directory.
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.8/site-packages/dash/dash.py", line 1461, in dispatch
    response.set_data(self.callback_map[output]["callback"](*args))
  File "/opt/conda/lib/python3.8/site-packages/dash/dash.py", line 1341, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/PrimeDesign/web_app/app.py", line 3607, in run_primedesign
    with open('/PrimeDesign/web_app/crispritz_output_%s.scores.txt' % session_id, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/PrimeDesign/web_app/crispritz_output_20210227_12.39.33.61.scores.txt'
172.17.0.1 - - [27/Feb/2021:00:39:52 +0000] "POST /_dash-update-component HTTP/1.1" 500 290 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:58 +0000] "POST /_dash-update-component HTTP/1.1" 200 139 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:59 +0000] "POST /_dash-update-component HTTP/1.1" 200 83 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
172.17.0.1 - - [27/Feb/2021:00:39:59 +0000] "POST /_dash-update-component HTTP/1.1" 200 359 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
ERROR! /PrimeDesign/hg38_chromosomes is not a directory.
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.8/site-packages/dash/dash.py", line 1461, in dispatch
    response.set_data(self.callback_map[output]["callback"](*args))
  File "/opt/conda/lib/python3.8/site-packages/dash/dash.py", line 1341, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/PrimeDesign/web_app/app.py", line 3607, in run_primedesign
    with open('/PrimeDesign/web_app/crispritz_output_%s.scores.txt' % session_id, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/PrimeDesign/web_app/crispritz_output_20210227_12.39.33.61.scores.txt'
172.17.0.1 - - [27/Feb/2021:00:39:59 +0000] "POST /_dash-update-component HTTP/1.1" 500 290 "http://localhost:9994/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"

`

Thank you!

**Comment by McDonald-li** [comment]
Hello, 
I encountered the same problem, and  it seems that there are no parameters about CFD score.
Have you resolve this issue later?
